### ISSUE TITLE
"WT_Alternating_Lower/Upper" --> "Upper"

### ISSUE THREAD

**Issue by verbalizer** [marvinki/verbalizer#4]
In the ontology "cluster6ontology_complete.rdf" click *>Workout_Template >WT_Alternating_Lower/Upper*. 
Then in the *Class Annotations Tab*, at the *SubClass Of* Section, click the question mark for *Workout_Template* to get the explanation.

***here comes the misbehaviour:***
it says :
*That's already stated in the ontology. Upper is workout template*

but it is supposed to say :
*That's already stated in the ontology. **WT_Alternating_Lower/Upper** is workout template*

check out the screen shot 
![bildschirmfoto vom 2016-11-03 09 47 35](https://cloud.githubusercontent.com/assets/21077965/19960339/7a611b78-a1ac-11e6-9b94-8ff8017c428e.png)

**Comment by f3l1xp** [comment]
outdated/not relevant anymore
