### ISSUE TITLE
OutOfMemory Exception 

### ISSUE THREAD

**Issue by f3l1xp** [marvinki/verbalizer#9]
OutOfMemory Exception when requesting any explanation for "Config" and Subclasses:

![outofmemory](https://user-images.githubusercontent.com/20476642/28366255-33e6766a-6c8c-11e7-8500-18632cb161ee.png)

**Comment by marvinki** [comment]
The offending "subclasschain" rule has been rewritten, so that it doesn't get stuck in loops any more.
